controller:
  image:
    registry: "docker.io"
    repository: "jenkins/jenkins"
    tag: "lts-jdk17"
  serviceType: LoadBalancer
  servicePort: 8080
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  admin:
    username: admin
    password: admin

persistence:
  enabled: false

agent:
  enabled: true