apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
data:
  POSTGRES_HOST: {{ .Values.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.env.POSTGRES_PORT | quote }}
  POSTGRES_NAME: {{ .Values.env.POSTGRES_NAME | quote }}
  POSTGRES_USER: {{ .Values.env.POSTGRES_USER | quote }}