apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "django-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: {{ toYaml .Values.command | nindent 12 }}
          args: {{ toYaml .Values.args | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "django-app.fullname" . }}-config
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.env.POSTGRES_PASSWORD | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}