# Визначаємо серверний блок, який відповідає за обробку HTTP-запитів
server {
    # Вказуємо порт, на якому Nginx слухатиме запити
    listen 80;

    # Налаштовуємо обробку запитів для кореневого маршруту "/"
    location / {
        # Передаємо запити до бекенд-сервера Django (контейнер "django")
        proxy_pass http://django:8000;
        
        # Установлюємо заголовок Host, щоб він відповідав оригінальному домену клієнта
        proxy_set_header Host $host;
        
        # Передаємо реальну IP-адресу клієнта
        proxy_set_header X-Real-IP $remote_addr;
        
        # Передаємо ланцюжок IP-адрес через проксі
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}